name: turbo_mysql
description: A high-performance MySQL client powered by Rust FFI.
version: 0.0.1
repository: https://github.com/alessandro-amos/turbo_mysql

environment:
  sdk: ^3.10.4

# Add regular dependencies here.
dependencies:
  code_assets: ^1.0.0
  ffi: ^2.2.0
  hooks: ^1.0.1
  # path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
